/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cofre {
  'id' : bigint,
  'regrasAcesso' : RegrasAcesso,
  'descricao' : string,
  'nome' : string,
  'notas' : Array<Nota>,
  'proprietario' : Principal,
}
export interface Contato { 'nome' : string, 'principalId' : Principal }
export interface Nota {
  'id' : bigint,
  'titulo' : string,
  'conteudo' : string,
  'dataModificacao' : Time,
  'dataCriacao' : Time,
}
export interface RegrasAcesso {
  'usuariosAutorizados' : Array<Principal>,
  'periodoInatividade' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'principalId' : string }
export interface UserProfileEntry {
  'nome' : string,
  'role' : UserRole,
  'principalId' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'adicionarContato' : ActorMethod<[Principal], undefined>,
  'adicionarNota' : ActorMethod<[bigint, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'atualizarUltimoAcessoBackend' : ActorMethod<[], undefined>,
  'buscarCofrePorId' : ActorMethod<[bigint], Cofre>,
  'criarCofre' : ActorMethod<[string, string, RegrasAcesso], bigint>,
  'editarCofre' : ActorMethod<
    [bigint, string, string, RegrasAcesso],
    undefined
  >,
  'editarNota' : ActorMethod<[bigint, bigint, string, string], undefined>,
  'excluirCofre' : ActorMethod<[bigint], undefined>,
  'excluirNota' : ActorMethod<[bigint, bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listarCofresUsuario' : ActorMethod<[], Array<Cofre>>,
  'listarContatos' : ActorMethod<[], Array<Contato>>,
  'listarNotas' : ActorMethod<[bigint], Array<Nota>>,
  /**
   * / Lista todos os perfis registrados (somente administradores)
   */
  'listarTodosProfiles' : ActorMethod<[], Array<UserProfileEntry>>,
  'obterUltimoAcesso' : ActorMethod<[Principal], Time>,
  /**
   * / Promove um usuário a administrador (somente administradores podem fazer isso)
   */
  'promoverParaAdmin' : ActorMethod<
    [Principal],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'removerContato' : ActorMethod<[Principal], undefined>,
  /**
   * / Revoga o status de administrador de um usuário (somente administradores podem fazer isso)
   * / O primeiro administrador do sistema não pode ter seu status revogado
   */
  'revogarAdmin' : ActorMethod<
    [Principal],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'revogarAutorizacao' : ActorMethod<[bigint, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Verifica se o caller tem acesso ao cofre (para polling de status de bloqueio).
   * / Retorna true = cofre acessível (desbloqueado), false = cofre trancado.
   * / NÃO atualiza o último acesso — seguro para polling frequente.
   */
  'verificarAcessoCofre' : ActorMethod<[bigint], boolean>,
  /**
   * / Returns the encrypted derived key for the caller (auth required)
   */
  'vetkd_encrypted_key' : ActorMethod<[Uint8Array, bigint], Uint8Array>,
  /**
   * / Returns the canister base public key (empty context), used to verify vetKeys
   * / derived with context=[] and input=cofreIdToBytes(cofreId) in vetkd_encrypted_key.
   * / Access controlled — only cofre owner or authorized users (with inactivity met) may call this.
   */
  'vetkd_public_key' : ActorMethod<[bigint], Uint8Array>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];