/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RegrasAcesso = IDL.Record({
  'usuariosAutorizados' : IDL.Vec(IDL.Principal),
  'periodoInatividade' : IDL.Int,
});
export const Time = IDL.Int;
export const Nota = IDL.Record({
  'id' : IDL.Nat,
  'titulo' : IDL.Text,
  'conteudo' : IDL.Text,
  'dataModificacao' : Time,
  'dataCriacao' : Time,
});
export const Cofre = IDL.Record({
  'id' : IDL.Nat,
  'regrasAcesso' : RegrasAcesso,
  'descricao' : IDL.Text,
  'nome' : IDL.Text,
  'notas' : IDL.Vec(Nota),
  'proprietario' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'principalId' : IDL.Text,
});
export const Contato = IDL.Record({
  'nome' : IDL.Text,
  'principalId' : IDL.Principal,
});
export const UserProfileEntry = IDL.Record({
  'nome' : IDL.Text,
  'role' : UserRole,
  'principalId' : IDL.Principal,
});

export const idlService = IDL.Service({
  'adicionarContato' : IDL.Func([IDL.Principal], [], []),
  'adicionarNota' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'atualizarUltimoAcessoBackend' : IDL.Func([], [], []),
  'buscarCofrePorId' : IDL.Func([IDL.Nat], [Cofre], []),
  'criarCofre' : IDL.Func([IDL.Text, IDL.Text, RegrasAcesso], [IDL.Nat], []),
  'editarCofre' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, RegrasAcesso], [], []),
  'editarNota' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'excluirCofre' : IDL.Func([IDL.Nat], [], []),
  'excluirNota' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listarCofresUsuario' : IDL.Func([], [IDL.Vec(Cofre)], []),
  'listarContatos' : IDL.Func([], [IDL.Vec(Contato)], ['query']),
  'listarNotas' : IDL.Func([IDL.Nat], [IDL.Vec(Nota)], []),
  'listarTodosProfiles' : IDL.Func([], [IDL.Vec(UserProfileEntry)], ['query']),
  'obterUltimoAcesso' : IDL.Func([IDL.Principal], [Time], ['query']),
  'promoverParaAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'removerContato' : IDL.Func([IDL.Principal], [], []),
  'revogarAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'revogarAutorizacao' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'verificarAcessoCofre' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'vetkd_encrypted_key' : IDL.Func(
      [IDL.Vec(IDL.Nat8), IDL.Nat],
      [IDL.Vec(IDL.Nat8)],
      [],
    ),
  'vetkd_public_key' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat8)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RegrasAcesso = IDL.Record({
    'usuariosAutorizados' : IDL.Vec(IDL.Principal),
    'periodoInatividade' : IDL.Int,
  });
  const Time = IDL.Int;
  const Nota = IDL.Record({
    'id' : IDL.Nat,
    'titulo' : IDL.Text,
    'conteudo' : IDL.Text,
    'dataModificacao' : Time,
    'dataCriacao' : Time,
  });
  const Cofre = IDL.Record({
    'id' : IDL.Nat,
    'regrasAcesso' : RegrasAcesso,
    'descricao' : IDL.Text,
    'nome' : IDL.Text,
    'notas' : IDL.Vec(Nota),
    'proprietario' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const Contato = IDL.Record({
    'nome' : IDL.Text,
    'principalId' : IDL.Principal,
  });
  const UserProfileEntry = IDL.Record({
    'nome' : IDL.Text,
    'role' : UserRole,
    'principalId' : IDL.Principal,
  });
  
  return IDL.Service({
    'adicionarContato' : IDL.Func([IDL.Principal], [], []),
    'adicionarNota' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'atualizarUltimoAcessoBackend' : IDL.Func([], [], []),
    'buscarCofrePorId' : IDL.Func([IDL.Nat], [Cofre], []),
    'criarCofre' : IDL.Func([IDL.Text, IDL.Text, RegrasAcesso], [IDL.Nat], []),
    'editarCofre' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, RegrasAcesso],
        [],
        [],
      ),
    'editarNota' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'excluirCofre' : IDL.Func([IDL.Nat], [], []),
    'excluirNota' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listarCofresUsuario' : IDL.Func([], [IDL.Vec(Cofre)], []),
    'listarContatos' : IDL.Func([], [IDL.Vec(Contato)], ['query']),
    'listarNotas' : IDL.Func([IDL.Nat], [IDL.Vec(Nota)], []),
    'listarTodosProfiles' : IDL.Func(
        [],
        [IDL.Vec(UserProfileEntry)],
        ['query'],
      ),
    'obterUltimoAcesso' : IDL.Func([IDL.Principal], [Time], ['query']),
    'promoverParaAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'removerContato' : IDL.Func([IDL.Principal], [], []),
    'revogarAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'revogarAutorizacao' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'verificarAcessoCofre' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'vetkd_encrypted_key' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Nat],
        [IDL.Vec(IDL.Nat8)],
        [],
      ),
    'vetkd_public_key' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat8)], []),
  });
};

export const init = ({ IDL }) => { return []; };