/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RegrasAcesso {
    usuariosAutorizados: Array<Principal>;
    periodoInatividade: bigint;
}
export type Time = bigint;
export interface Nota {
    id: bigint;
    titulo: string;
    conteudo: string;
    dataModificacao: Time;
    dataCriacao: Time;
}
export interface UserProfileEntry {
    nome: string;
    role: UserRole;
    principalId: Principal;
}
export interface Contato {
    nome: string;
    principalId: Principal;
}
export interface UserProfile {
    name: string;
    principalId: string;
}
export interface Cofre {
    id: bigint;
    regrasAcesso: RegrasAcesso;
    descricao: string;
    nome: string;
    notas: Array<Nota>;
    proprietario: Principal;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    adicionarContato(principalId: Principal): Promise<void>;
    adicionarNota(idCofre: bigint, titulo: string, conteudo: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    atualizarUltimoAcessoBackend(): Promise<void>;
    buscarCofrePorId(idCofre: bigint): Promise<Cofre>;
    criarCofre(nome: string, descricao: string, regras: RegrasAcesso): Promise<bigint>;
    editarCofre(idCofre: bigint, nome: string, descricao: string, regras: RegrasAcesso): Promise<void>;
    editarNota(idCofre: bigint, idNota: bigint, novoTitulo: string, novoConteudo: string): Promise<void>;
    excluirCofre(idCofre: bigint): Promise<void>;
    excluirNota(idCofre: bigint, idNota: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listarCofresUsuario(): Promise<Array<Cofre>>;
    listarContatos(): Promise<Array<Contato>>;
    listarNotas(idCofre: bigint): Promise<Array<Nota>>;
    /**
     * / Lista todos os perfis registrados (somente administradores)
     */
    listarTodosProfiles(): Promise<Array<UserProfileEntry>>;
    obterUltimoAcesso(usuario: Principal): Promise<Time>;
    /**
     * / Promove um usuário a administrador (somente administradores podem fazer isso)
     */
    promoverParaAdmin(user: Principal): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removerContato(principalId: Principal): Promise<void>;
    /**
     * / Revoga o status de administrador de um usuário (somente administradores podem fazer isso)
     * / O primeiro administrador do sistema não pode ter seu status revogado
     */
    revogarAdmin(user: Principal): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    revogarAutorizacao(idCofre: bigint, usuario: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Verifica se o caller tem acesso ao cofre (para polling de status de bloqueio).
     * / Retorna true = cofre acessível (desbloqueado), false = cofre trancado.
     * / NÃO atualiza o último acesso — seguro para polling frequente.
     */
    verificarAcessoCofre(idCofre: bigint): Promise<boolean>;
    /**
     * / Returns the encrypted derived key for the caller (auth required)
     */
    vetkd_encrypted_key(transportPublicKey: Uint8Array, cofreId: bigint): Promise<Uint8Array>;
    /**
     * / Returns the canister base public key (empty context), used to verify vetKeys
     * / derived with context=[] and input=cofreIdToBytes(cofreId) in vetkd_encrypted_key.
     * / Access controlled — only cofre owner or authorized users (with inactivity met) may call this.
     */
    vetkd_public_key(idCofre: bigint): Promise<Uint8Array>;
}
import type { UserProfile as _UserProfile, UserProfileEntry as _UserProfileEntry, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adicionarContato(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adicionarContato(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adicionarContato(arg0);
            return result;
        }
    }
    async adicionarNota(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adicionarNota(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adicionarNota(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async atualizarUltimoAcessoBackend(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.atualizarUltimoAcessoBackend();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.atualizarUltimoAcessoBackend();
            return result;
        }
    }
    async buscarCofrePorId(arg0: bigint): Promise<Cofre> {
        if (this.processError) {
            try {
                const result = await this.actor.buscarCofrePorId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buscarCofrePorId(arg0);
            return result;
        }
    }
    async criarCofre(arg0: string, arg1: string, arg2: RegrasAcesso): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.criarCofre(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.criarCofre(arg0, arg1, arg2);
            return result;
        }
    }
    async editarCofre(arg0: bigint, arg1: string, arg2: string, arg3: RegrasAcesso): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editarCofre(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editarCofre(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async editarNota(arg0: bigint, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editarNota(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editarNota(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async excluirCofre(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.excluirCofre(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.excluirCofre(arg0);
            return result;
        }
    }
    async excluirNota(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.excluirNota(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.excluirNota(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listarCofresUsuario(): Promise<Array<Cofre>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarCofresUsuario();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarCofresUsuario();
            return result;
        }
    }
    async listarContatos(): Promise<Array<Contato>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarContatos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarContatos();
            return result;
        }
    }
    async listarNotas(arg0: bigint): Promise<Array<Nota>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarNotas(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarNotas(arg0);
            return result;
        }
    }
    async listarTodosProfiles(): Promise<Array<UserProfileEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarTodosProfiles();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarTodosProfiles();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async obterUltimoAcesso(arg0: Principal): Promise<Time> {
        if (this.processError) {
            try {
                const result = await this.actor.obterUltimoAcesso(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obterUltimoAcesso(arg0);
            return result;
        }
    }
    async promoverParaAdmin(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.promoverParaAdmin(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoverParaAdmin(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async removerContato(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removerContato(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removerContato(arg0);
            return result;
        }
    }
    async revogarAdmin(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.revogarAdmin(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revogarAdmin(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async revogarAutorizacao(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revogarAutorizacao(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revogarAutorizacao(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async verificarAcessoCofre(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verificarAcessoCofre(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verificarAcessoCofre(arg0);
            return result;
        }
    }
    async vetkd_encrypted_key(arg0: Uint8Array, arg1: bigint): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor.vetkd_encrypted_key(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.vetkd_encrypted_key(arg0, arg1);
            return result;
        }
    }
    async vetkd_public_key(arg0: bigint): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor.vetkd_public_key(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.vetkd_public_key(arg0);
            return result;
        }
    }
}
function from_candid_UserProfileEntry_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileEntry): UserProfileEntry {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nome: string;
    role: _UserRole;
    principalId: Principal;
}): {
    nome: string;
    role: UserRole;
    principalId: Principal;
} {
    return {
        nome: value.nome,
        role: from_candid_UserRole_n4(_uploadFile, _downloadFile, value.role),
        principalId: value.principalId
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfileEntry>): Array<UserProfileEntry> {
    return value.map((x)=>from_candid_UserProfileEntry_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
